"""Capture durable proof of the Snowflake build before the trial expires.

The live runtime needs no warehouse (it runs on committed Parquet + DuckDB), so once the
Snowflake trial ends the warehouse is gone and the headline README numbers — 41M silver rows,
the gold table sizes, the ~$1 credit cost — can no longer be reproduced. This script connects
with the .env credentials, reads those facts, and writes them to a committed markdown file
(docs/snowflake_evidence.md) so they survive as verifiable evidence.

Read-only. Run once while the trial is still active:
    .venv/Scripts/python ingestion/snowflake_evidence.py
"""

import os
from datetime import datetime, timezone
from pathlib import Path

import snowflake.connector
from dotenv import load_dotenv

ROOT = Path(__file__).resolve().parents[1]
load_dotenv(ROOT / ".env")
OUT = ROOT / "docs" / "snowflake_evidence.md"

# Standard-edition list rate (AWS) used only to translate credits → an indicative $ figure.
# Trial credits are free, so real spend is $0; this shows what the build "would" have cost.
USD_PER_CREDIT = 2.0


def _rows(cur, sql: str) -> list[tuple]:
    cur.execute(sql)
    return cur.fetchall()


def main() -> None:
    conn = snowflake.connector.connect(
        account=os.environ["SNOWFLAKE_ACCOUNT"],
        user=os.environ["SNOWFLAKE_USER"],
        password=os.environ["SNOWFLAKE_PASSWORD"],
        role=os.getenv("SNOWFLAKE_ROLE") or "ACCOUNTADMIN",
        warehouse=os.getenv("SNOWFLAKE_WAREHOUSE") or "TFL_WH",
        database=os.getenv("SNOWFLAKE_DATABASE") or "TFL",
    )
    lines: list[str] = []

    def section(title: str, sql: str, render) -> None:
        """Run one query; render its rows, or record the error — so partial evidence still saves."""
        lines.append(f"\n## {title}\n")
        try:
            rows = _rows(conn.cursor(), sql)
            lines.extend(render(rows))
            print(f"[OK] {title}")
        except Exception as exc:  # keep going — capture whatever the account still allows
            lines.append(f"_Unavailable: {type(exc).__name__}: {str(exc)[:160]}_")
            print(f"[skip] {title}: {exc}")

    try:
        section(
            "Silver — unified journeys (the Spark backfill output)",
            "select count(*) from TFL.SILVER.JOURNEYS",
            lambda r: [f"**{r[0][0]:,} rows** in `TFL.SILVER.JOURNEYS` "
                       "(2022–2026, five file eras unified — see ADR-0002)."],
        )
        section(
            "Gold — tested star schema (row counts from metadata)",
            """select table_name, row_count, round(bytes/1024/1024, 1) as mb
               from TFL.INFORMATION_SCHEMA.TABLES
               where table_schema = 'GOLD' and table_type = 'BASE TABLE'
               order by row_count desc""",
            lambda r: ["| table | rows | MB |", "|---|---:|---:|",
                       *[f"| `{t}` | {int(n or 0):,} | {mb} |" for t, n, mb in r]],
        )
        section(
            "Warehouse cost (credits consumed on the trial)",
            """select warehouse_name, round(sum(credits_used), 3) as credits
               from table(TFL.INFORMATION_SCHEMA.WAREHOUSE_METERING_HISTORY(
                   dateadd('day', -120, current_timestamp()), current_timestamp()))
               group by warehouse_name order by credits desc""",
            lambda r: ["| warehouse | credits | ≈ USD (Standard list) |", "|---|---:|---:|",
                       *[f"| `{w}` | {c} | ${float(c) * USD_PER_CREDIT:.2f} |" for w, c in r],
                       f"\n_Trial credits are free (real spend $0); at the Standard list rate "
                       f"(~${USD_PER_CREDIT:.0f}/credit) the whole build would have cost about a dollar._"],
        )
    finally:
        conn.close()

    stamp = datetime.now(timezone.utc).strftime("%Y-%m-%d %H:%M UTC")
    header = (
        "# Snowflake build — captured evidence\n\n"
        f"Generated by `ingestion/snowflake_evidence.py` on **{stamp}**, while the Snowflake trial "
        "was still active. **The live runtime does not use Snowflake** — it runs on committed "
        "Parquet + DuckDB (ADR-0005/0006). This file preserves the warehouse-side facts (which the "
        "README cites) so they stay verifiable after the trial expires and the warehouse is gone.\n"
    )
    OUT.write_text(header + "\n".join(lines) + "\n", encoding="utf-8")
    print(f"\nwrote {OUT.relative_to(ROOT).as_posix()}")


if __name__ == "__main__":
    main()
