// TfL Cycle-Hire — semantic model expressed as TMDL (Tabular Model Definition Language),
// the model-as-code that underpins the Power BI report. This is the star schema: fact tables
// (flows, journeys, deviation, live) each relate to shared dimensions (dim_date, dim_station).
//
// STATUS: hand-authored from the committed Parquet schemas and cross-checked against DuckDB.
// It has NOT been opened/verified in Power BI Desktop in this environment — treat it as the
// model spec. The guaranteed build path is powerbi/README.md (blank project + paste M + DAX);
// Tabular Editor users can also consume this TMDL directly.
//
// Only the columns used by measures/relationships/pages are listed; Power BI infers the full
// column set from each Parquet source on refresh. Measures live in powerbi/measures.dax.

// ── Parameter: where the committed gold Parquet lives (set per your local clone) ──
expression GoldExportFolder =
        "C:\dev\portfolio\tfl-data-engineering\app\gold_export" meta [
    IsParameterQuery = true,
    Type = "Text",
    IsParameterQueryRequired = true
]

// ─────────────────────────────  Dimensions  ─────────────────────────────

table dim_date
    column date_key
        dataType: int64
        sourceColumn: date_key
        isKey: true
    column date_day
        dataType: dateTime
        sourceColumn: date_day
    column year
        dataType: int64
        sourceColumn: year
    column month_name
        dataType: string
        sourceColumn: month_name
    column day_name
        dataType: string
        sourceColumn: day_name
    column is_weekend
        dataType: boolean
        sourceColumn: is_weekend

    partition dim_date = m
        mode: import
        source = ```
                let
                    Source = Parquet.Document(File.Contents(GoldExportFolder & "\dim_date.parquet"))
                in
                    Source
            ```

table dim_station
    column station_key
        dataType: string
        sourceColumn: station_key
        isKey: true
    column station_name
        dataType: string
        sourceColumn: station_name
    column dock_events
        dataType: int64
        sourceColumn: dock_events

    partition dim_station = m
        mode: import
        source = ```
                let
                    Source = Parquet.Document(File.Contents(GoldExportFolder & "\dim_station.parquet"))
                in
                    Source
            ```

// ─────────────────────────────  Facts  ─────────────────────────────

// Deliberately disconnected: certified ADR-0009 cards must not change under
// date/station slicers. The rigor export, not DAX, owns this result.
table certified_adr0009_evidence
    column evidence_artifact
        dataType: string
        sourceColumn: evidence_artifact
    column certificate_id
        dataType: string
        sourceColumn: certificate_id
        isKey: true
    column evidence_version
        dataType: string
        sourceColumn: evidence_version
    column adr_id
        dataType: string
        sourceColumn: adr_id
    column claim_class
        dataType: string
        sourceColumn: claim_class
    column permitted_claim
        dataType: string
        sourceColumn: permitted_claim
    column comparator_family
        dataType: string
        sourceColumn: comparator_family
    column cited_strike_seed
        dataType: string
        sourceColumn: cited_strike_seed
    column station_day_evidence
        dataType: string
        sourceColumn: station_day_evidence
    column min_expected_departures
        dataType: int64
        sourceColumn: min_expected_departures
    column headline_ratio
        dataType: double
        sourceColumn: headline_ratio
    column ci95_lo
        dataType: double
        sourceColumn: ci95_lo
    column ci95_hi
        dataType: double
        sourceColumn: ci95_hi
    column n_events
        dataType: int64
        sourceColumn: n_events

    partition certified_adr0009_evidence = m
        mode: import
        source = ```
                let
                    Source = Json.Document(File.Contents(GoldExportFolder & "\analysis_rigor.json")),
                    Certificate = Source[certificate],
                    Headline = Source[headline]
                in
                    #table({"evidence_artifact", "certificate_id", "evidence_version", "adr_id", "claim_class", "permitted_claim", "comparator_family", "cited_strike_seed", "station_day_evidence", "min_expected_departures", "headline_ratio", "ci95_lo", "ci95_hi", "n_events"}, {{"app/gold_export/analysis_rigor.json", Certificate[certificate_id], Certificate[evidence_version], Certificate[adr_id], Certificate[claim_class], Certificate[permitted_claim], Certificate[primary_specification][comparator_family], Certificate[primary_specification][strike_seed], "app/gold_export/demand_deviation.parquet", Certificate[primary_specification][min_expected_departures], Headline[median_ratio], Headline[ci95_lo], Headline[ci95_hi], Headline[n_events]}})
            ```

    measure 'Certified ADR-0009 Demand Ratio' =
            MAX ( certified_adr0009_evidence[headline_ratio] )
        formatString: 0.000
        displayFolder: T-CERT
        description: The locked ADR-0009 historical observed association. This is not calculated from report rows.

    measure 'Certified ADR-0009 Lower CI' =
            MAX ( certified_adr0009_evidence[ci95_lo] )
        formatString: 0.000
        displayFolder: T-CERT
        description: Lower bound of the rigor-owned 95 percent confidence interval.

    measure 'Certified ADR-0009 Upper CI' =
            MAX ( certified_adr0009_evidence[ci95_hi] )
        formatString: 0.000
        displayFolder: T-CERT
        description: Upper bound of the rigor-owned 95 percent confidence interval.

    measure 'Certified ADR-0009 Claim' =
            MAX ( certified_adr0009_evidence[permitted_claim] )
        displayFolder: T-CERT
        description: The permitted associational language from the evidence certificate.

table daily_journey_stats
    column date_key
        dataType: int64
        sourceColumn: date_key
    column journeys
        dataType: int64
        sourceColumn: journeys
    column ebike_journeys
        dataType: int64
        sourceColumn: ebike_journeys
    column avg_duration_min
        dataType: double
        sourceColumn: avg_duration_min
    column is_weekend
        dataType: boolean
        sourceColumn: is_weekend

    partition daily_journey_stats = m
        mode: import
        source = ```
                let
                    Source = Parquet.Document(File.Contents(GoldExportFolder & "\daily_journey_stats.parquet"))
                in
                    Source
            ```

table station_daily_flows
    column date_key
        dataType: int64
        sourceColumn: date_key
    column station_key
        dataType: string
        sourceColumn: station_key
    column departures
        dataType: int64
        sourceColumn: departures
    column arrivals
        dataType: int64
        sourceColumn: arrivals
    column net_inflow
        dataType: int64
        sourceColumn: net_inflow

    partition station_daily_flows = m
        mode: import
        source = ```
                let
                    Source = Parquet.Document(File.Contents(GoldExportFolder & "\station_daily_flows.parquet"))
                in
                    Source
            ```

table demand_deviation
    column date_key
        dataType: int64
        sourceColumn: date_key
    column station_key
        dataType: string
        sourceColumn: station_key
    column expected_departures
        dataType: double
        sourceColumn: expected_departures
    column deviation
        dataType: double
        sourceColumn: deviation
    column deviation_ratio
        dataType: double
        sourceColumn: deviation_ratio
    column is_disruption
        dataType: boolean
        sourceColumn: is_disruption

    partition demand_deviation = m
        mode: import
        source = ```
                let
                    Source = Parquet.Document(File.Contents(GoldExportFolder & "\demand_deviation.parquet"))
                in
                    Source
            ```

table demand_deviation_ml
    column date_key
        dataType: int64
        sourceColumn: date_key
    column station_key
        dataType: string
        sourceColumn: station_key
    column deviation
        dataType: double
        sourceColumn: deviation
    column deviation_ratio
        dataType: double
        sourceColumn: deviation_ratio
    column is_disruption
        dataType: boolean
        sourceColumn: is_disruption

    partition demand_deviation_ml = m
        mode: import
        source = ```
                let
                    Source = Parquet.Document(File.Contents(GoldExportFolder & "\demand_deviation_ml.parquet"))
                in
                    Source
            ```

// ─────────────────────────────  Live layer  ─────────────────────────────

table live_line_status
    column snapshot_date
        dataType: string
        sourceColumn: snapshot_date
    column line_name
        dataType: string
        sourceColumn: line_name
    column mode
        dataType: string
        sourceColumn: mode
    column status_description
        dataType: string
        sourceColumn: status_description
    column is_good_service
        dataType: boolean
        sourceColumn: is_good_service
    column reason
        dataType: string
        sourceColumn: reason

    partition live_line_status = m
        mode: import
        source = ```
                let
                    Source = Parquet.Document(File.Contents(GoldExportFolder & "\live_line_status.parquet"))
                in
                    Source
            ```

table live_bikepoint
    column snapshot_date
        dataType: string
        sourceColumn: snapshot_date
    column bikepoint_id
        dataType: string
        sourceColumn: bikepoint_id
    column common_name
        dataType: string
        sourceColumn: common_name
    column lat
        dataType: double
        sourceColumn: lat
    column lon
        dataType: double
        sourceColumn: lon
    column n_bikes
        dataType: int64
        sourceColumn: n_bikes
    column n_empty_docks
        dataType: int64
        sourceColumn: n_empty_docks
    column fill_rate
        dataType: double
        sourceColumn: fill_rate

    partition live_bikepoint = m
        mode: import
        source = ```
                let
                    Source = Parquet.Document(File.Contents(GoldExportFolder & "\live_bikepoint.parquet"))
                in
                    Source
            ```

// ─────────────────────────────  Relationships  ─────────────────────────────
// Single-direction (dimension filters fact). date_key → dim_date, station_key → dim_station.

relationship flows_date
    fromColumn: station_daily_flows.date_key
    toColumn: dim_date.date_key

relationship flows_station
    fromColumn: station_daily_flows.station_key
    toColumn: dim_station.station_key

relationship journeys_date
    fromColumn: daily_journey_stats.date_key
    toColumn: dim_date.date_key

relationship deviation_date
    fromColumn: demand_deviation.date_key
    toColumn: dim_date.date_key

relationship deviation_station
    fromColumn: demand_deviation.station_key
    toColumn: dim_station.station_key

relationship deviation_ml_date
    fromColumn: demand_deviation_ml.date_key
    toColumn: dim_date.date_key

relationship deviation_ml_station
    fromColumn: demand_deviation_ml.station_key
    toColumn: dim_station.station_key
